### ISSUE TITLE
/site/settings.json

### ISSUE THREAD

**Issue by BenLubar** [SockDrawer/SockSite#117]
`/site/settings.json` doesn't exist in NodeBB and SockSite is sending a bunch of requests with no User-Agent, Accept, or Referrer headers, which is making it hard to monitor for malicious activity.

**Comment by AccaliaDeElementia** [comment]
this should be resolved by 4e26481

Please confirm that this issue is no longer extant at your earliest convenience and reopen this ticket if issue persists.
