### ISSUE TITLE
AJAX updates do not change image when site goes down

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockSite#27]
When WTDWTF  was working, the header image says "IS YOU". When WTDWTF then goes down, the new data streams in... but the header still says "IS YOU"

![image](https://cloud.githubusercontent.com/assets/1219256/7217283/ea524d7a-e5ed-11e4-98c4-32261bad986d.png)

**Comment by TwelveBaud** [comment]
AJAX updates don't change the flavor text either.

**Comment by Onyx47** [comment]
Damn, you're right. That got ripped out when I switched to partial reloading as to not mess with the Discodefinition of the moment.
