### ISSUE TITLE
"Bad" results still claim the site is up

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockSite#28]
When the site is responding with "bad" metrics, the header should say "IS DISCOURSE", because that's clearly server cooties. 

This is not a working site:

![image](https://cloud.githubusercontent.com/assets/1219256/7217284/14c2b5fe-e5ee-11e4-9561-ef9095221f91.png)

**Comment by Onyx47** [comment]
Triaged by 58d9fdf414c82e5a28e144e1c82fa1e077e8e6a8

Should be servicable until we get the new scoring system going.

**Comment by AccaliaDeElementia** [comment]
i'll be tackling the new scoring system tonight and tomorrow.

it'll be the same one that i use in `/raw` up will be score > 50%

expect updates

**Comment by AccaliaDeElementia** [comment]
this should be fixed by moving to discoappdex scoring as of 489045571d

monitored site is considered "up" if it has an overall score >= 50

This change has been merged into master and should be deployed shortly.
