### ISSUE TITLE
Mixed Content Warnings for DiscoDefinition-Embedded Images

### ISSUE THREAD

**Issue by TwelveBaud** [SockDrawer/SockSite#39]
When a DiscoDefinition includes an image, it's usually hosted on Discourse itself. Because The Daily WTF's installation does not support HTTPS and in any case does not use HTTPS by default, these images are loaded as [mixed display content](https://developer.mozilla.org/en-US/docs/Security/MixedContent#Mixed_passive.2Fdisplay_content) and a warning is logged in the console. For some crazy raisin, Google Chrome and Mozilla Firefox are deprecating this functionality and intend to remove it as soon as possible, so these images may disappear. In any case, they "break the lock" in the address bar.

Rewriting these URLs to use HTTPS is not possible since the server does not support HTTPS. We can proxy these images, but [we don't currently plan to](http://what.thedailywtf.com/t/isitjustmeorservercooties-com-development-thread-and-onyx-notification-spam/37172/1126?u=twelvebaud).

_Short-term Solution:_ None. The images currently load and render in all current browsers; aside from a warning in the console, scary imagery in the address bar, and leaking information about which DiscoDefinition is being viewed, everything's working properly.

_Long-term Solution:_ Contact Alex Papadimoulis at @apapadimoulis (on the forums) and help him get SSL set up.

**Comment by AccaliaDeElementia** [comment]
Assigning @TwelveBaud to handle getting HTTPS set up on target site.

**Comment by Onyx47** [comment]
Just got hit by this, but it didn't even render for me on my cloud9 instance over HTTPS.

Can we confirm this is cloud9 problem only?

**Comment by TwelveBaud** [comment]
I can't confirm or deny anything about cloud9 but I _can_ confirm it still happens on the live site. (the four abarker avatars from the Discoparsing discodefinition)

![screenshot from 2015-06-03 16 32 23](https://cloud.githubusercontent.com/assets/1701040/7970767/39c468b8-0a0e-11e5-9bfe-45783d35771e.png)

**Comment by Onyx47** [comment]
But it _does_ render there, yes?

On cloud9 they wouldn't load at all.

**Comment by yamikuronue** [comment]
Seems to be resolved by TDWTF going to https
