### ISSUE TITLE
Refreshing page should not reset tab

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockSite#43]
Refreshing the page when on the graph tab should load the page with the graph tab open.

Likewise with the history tab.

**Comment by TwelveBaud** [comment]
[This](https://developer.mozilla.org/en-US/docs/Web/Guide/API/DOM/Manipulating_the_browser_history) may help, since you're not a DiscoDev and aren't going to spam it with every post number in every topic ever all the time.

**Comment by AccaliaDeElementia** [comment]
I was thinking of using anchors for that

as moving to an anchor generally does not add to the browser history and allows one to bookmark or send urls to link to a specific tab

that would make it be 
- https://servercooteis.com#status 
- https://servercooteis.com#history and 
- https://servercooteis.com#graph

;-)

**Comment by Onyx47** [comment]
Yes, I wanted to use the history API myself. It works rather well.

The question is why Bootstrap's tab control completely prevents updating the URL. I'll just have to do it manually...

**Comment by TwelveBaud** [comment]
must... resist urge... to edit... @accalias... must not... buy domain...

;-)

**Comment by AccaliaDeElementia** [comment]
you have my attention.....l what domain would you buy?

**Comment by TwelveBaud** [comment]
servercoot**<u>ei</u>**s.com

**Comment by AccaliaDeElementia** [comment]
ROFL

well if you want to ;-)

the server is:
45.55.146.244
2604:a880:800:10::76a:f001

accepts wildcard domains so go to town if you are so inclined.
