### ISSUE TITLE
Status messages missing in WebSocket data object

### ISSUE THREAD

**Issue by Onyx47** [SockDrawer/SockSite#46]
`data` object should contain server status and flavor messages to enable proper clientside rendering of templates based on WebSocket updates.

**Comment by AccaliaDeElementia** [comment]
server side resolved by dfbad99b790

onyx, web side's up to you now. ;-)

**Comment by Onyx47** [comment]
This is done as well, isn't it? We're fully WebSocket driven now, yes?

Yeah, being away from the project messes with my memory...

**Comment by AccaliaDeElementia** [comment]
i think we're good here.

we're live on websockets 100%
