### ISSUE TITLE
Cornify counter not resetting on page reload

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockSite#48]
It seems the cornify counter does not reset on page load (windows firefox).

Reproduction:
- Click the cornify button
- Witness the counter at the top of the screen
- Hit F5
- Click the cornify button
- Notice the counter at the top of the screen lists 1 more than it did before the reload, but only one unicorn or rainbow is visible.

**Comment by RaceProUK** [comment]
The cookie that holds the count is set by the Cornify script, which I'm including from their website; I'll see what I can do, but I can't guarantee anything :wink:

**Comment by AccaliaDeElementia** [comment]
what about doing this on document load?

```
document.cookie = 'CORNIFY_COOKIE_NAME=;expires='+new Date().toUTCString();
```

?

**Comment by RaceProUK** [comment]
Nope :cry:

**Comment by RaceProUK** [comment]
Thought it wasn't going to work. But then I put it in the right place :smile:
