### ISSUE TITLE
Is polling every 10 seconds too much?

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockSite#53]
I can't help but feel it's placing more load on the forum than strictly necessary, and contributing to the cooties; maybe once a minute is better?

**Comment by AccaliaDeElementia** [comment]
i'll admit i pulled the time out of my backside.

there's a balancing act here we need to poll fast enough that we're responsive but slow enough that we're not placing extra load on the site.

I think the current  rate might be too fast, but it's slower than one active person would generate.

once a minute might be too slow, maybe double the delay? poll at 6 seconds per poll, taking 24 seconds (not including the time spent waiting for reply) to cycle through the endpoints?

**Comment by Onyx47** [comment]
Maybe we could make it adaptable, depending on server status?

Then again, I'd rather have more updates when it's down, but we should actually poll less, which sounds counterintuitive...

**Comment by AccaliaDeElementia** [comment]
it's actually already adaptive. the countdown for the next poll doesn't start until the prior check completes

so when cooties strike we don't pile a bunch of outstanding polls on discourse.

**Comment by RaceProUK** [comment]
> i'll admit i pulled the time out of my backside

That would explain the smell… :laughing:

> once a minute might be too slow, maybe double the delay? poll at 6 seconds per poll, taking 24 seconds (not including the time spent waiting for reply) to cycle through the endpoints?

Sounds good to me :+1:

**Comment by AccaliaDeElementia** [comment]
done and done.

deployed at the new polling rate.

**Comment by RaceProUK** [comment]
*feels a stiff breeze for just a moment, it were that quick*
