### ISSUE TITLE
Implement desktop notifications for transitions from online to offline or visa versa

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockSite#63]

**Comment by AccaliaDeElementia** [comment]
referenct: 
http://what.thedailywtf.com/t/servercooties-com-development-thread-and-tracking/37172/2267?u=accalia

**Comment by riking** [comment]
https://github.com/discourse/discourse/blob/master/app/assets/javascripts/discourse/lib/desktop-notifications.js.es6#L138-L147

**Comment by AccaliaDeElementia** [comment]
implemented in 0ad58ac9 and ready for testing

**Comment by AccaliaDeElementia** [comment]
notifications should inclide date/timestamp of notification somewhere in them.
