### ISSUE TITLE
Overall HTTP code should be maximum not average

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockSite#72]
- No more confusing non-codes
- No more 3xx codes (Discourse never serves these on the endpoints we check)
- A better reflection of the true state of the forum

**Comment by Off-By-0ne** [comment]
I liked the average HTTP codes, it was nicely discoursistent.

They should have been rounded to 2 decimals though, so they don't look like real HTTP codes.

**Comment by AccaliaDeElementia** [comment]
hmm. using max is also messing with the discoapdex scores. it's artificially deflating them.

maybe use min instead of max? or round to decimal poitns as @Off-By-0ne suggests

**Comment by RaceProUK** [comment]
I don't see the issue with the DiscoApdex scores; after all, if the main page loads but threads don't (or vice versa), the forum is, for all practical purposes, busted :stuck_out_tongue:
