### ISSUE TITLE
Could we get a good icon for the notification, please?

### ISSUE THREAD

**Issue by Deamon-Kid** [SockDrawer/SockSite#86]
That white looks terrible!

![screenshot 2015-06-05 08 26 39](https://cloud.githubusercontent.com/assets/919508/8000581/d9fe2d06-0b5c-11e5-913d-79ebd30de332.png)

Filed Under: [I know all three Opera users will thank me for that](#tag)

**Comment by Onyx47** [comment]
I get white notifications. The hell?

Do you have a so-called "theme" of some kind installed? Because this is problematic: while I can export a better image, if the notification background isn't always white we can't count on the icon being visible.

Maybe we should place it inside a white circle, just in case?

**Comment by AccaliaDeElementia** [comment]
hmm... didn't realize that it was possible to have a non white background on those.

@onyx47 i think the best solution is to export a version with the white background as you suggested.

**Comment by Deamon-Kid** [comment]
![screenshot 2015-06-05 16 29 53](https://cloud.githubusercontent.com/assets/919508/8008168/b9871ae4-0ba0-11e5-910a-ec81b69bd128.png)
![screenshot 2015-06-05 16 29 30](https://cloud.githubusercontent.com/assets/919508/8008169/b99f74b8-0ba0-11e5-9542-8c065ba63451.png)

newest stable according to the about page.
Also apparently I am actually using a theme. Though I don't see it (as visible on the screenshots) and I never chose it. So it might be a thing that gets installed automatically.

Filed Under: [I like the idea of a good looking white border around the face but it seems to be cut off on the right side already so you might want to resize the inline image first.](#tag)

**Comment by Deamon-Kid** [comment]
Welp, "close and comment" does NOT mean "post the comment and then navigate away from here".
Sorry...

Somebody might want to reattach the "ready"-label. I don't know how you guys use them :D

**Comment by Onyx47** [comment]
Fixed #86 via 863069c

**Comment by Onyx47** [comment]
Working on a new one, Yami? The one I committed should be visible on any background colour already. Or do we want a distinct one?

**Comment by yamikuronue** [comment]
I had an outdated view that said this hadn't been moved into ready when you started working on it, my bad.
